symbols = ".*"

[accounts]

  [accounts.A1]
  master = true
  login = "YOUR_KUCOIN_FUTURES_API_KEY_GOES_HERE"
  password = "YOUR_KUCOIN_FUTURES_PASSPHRASE_GOES_HERE"
  secret = "YOUR_KUCOIN_FUTURES_SECRET_GOES_HERE"
  symbols = ".*"

[users]

  [users.trader]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ "XBTUSDM" ]

[rate_limits]

  [rate_limits.global]
  type = "ORDER_ACTION"
  aggregate = true
  request_limit = 100
  monitor_period = "10s"
  ban_period = "5m"

  [rate_limits.A]
  type = "CREATE_ORDER"
  accounts = "A.*"
  request_limit = 30
  monitor_period = "1s"
  ban_period = "5m"

  [rate_limits.market_maker]
  type = "CREATE_ORDER"
  users = [ "trader" ]
  request_limit = 20
  monitor_period = "200ms"
  ban_period = "5m"
